import {ICEBERG_STAGES} from './iceberg-content.js';
// 能力介绍的主内容。顺序固定为定义、用途、SQL，最后才是场景。
export const FEATURE_CONTENT = {
  git4data: {
    definition:'Git for Data 在本演示里以数据库快照与大表 Clone 为主：给某一时刻的数据命名，再创建可独立写入的候选库。Clone 共享已有数据块，不需要将百万行逐行复制；候选库的后续写入只形成自己的增量状态。',
    essence:'正式库与候选库从同一数据基线分出，既能做真实规模的 CI，也能隔离测试写入。',
    uses:[
      ['大表 CI','用百万行订单做回归和数据质量检查，避免只用几行假数据得到错误结论。'],
      ['变更验证','在候选库测试折扣、索引或查询，再比较正式库与候选库的结果。'],
      ['测试隔离','测试脚本可以故意写坏数据；源库仍可被独立查询和核对。'],
    ],
    sql:[
      {title:'为正式库创建快照',why:'固定 Clone 的数据起点，后续候选库从这个状态生成。',code:'CREATE SNAPSHOT demo_promo_base FOR DATABASE demo_shop;'},
      {title:'Clone 出候选库',why:'新建数据库元数据并共享已有数据块，无需将百万行逐行复制。元数据与后续写入仍会占用空间。',code:"CREATE DATABASE demo_shop_ci CLONE demo_shop {snapshot = 'demo_promo_base'};"},
      {title:'比较两边的大表',why:'确认 Clone 后源库和候选库均包含本次订单基线。',code:'SELECT COUNT(*) AS orders FROM demo_shop.orders;\nSELECT COUNT(*) AS orders FROM demo_shop_ci.orders;'},
      {title:'在候选库注入并修复错误',why:'让 CI 门禁真实失败一次，再核对源库没有被候选库写入影响。',code:'UPDATE demo_shop_ci.products SET price=-1 WHERE product_id=1;\nSELECT COUNT(*) AS invalid_products FROM demo_shop_ci.products WHERE price<=0;\nSELECT price FROM demo_shop.products WHERE product_id=1;'},
    ],
    deepDiveTitle:'从大表 Clone 到交付的完整流程',
    deepDive:[
      {title:'01 / 定义基线',body:'先准备一百万行订单，记录正式库行数和价格，再创建数据库快照。快照代表同一个确定的数据起点，CI 结果才有可比性。'},
      {title:'02 / 建立隔离候选库',body:'从快照 Clone 数据库，记录 Clone 耗时；分别查询源库和候选库的百万行订单。多团队开发时可各自 Clone 并行试验，完成后清理临时库。'},
      {title:'03 / 故意让门禁失败',body:'只在候选库写入负价，质量查询必须查出异常；修复后门禁从失败变为通过。再次查询正式库价格，证明测试写入被隔离。'},
      {title:'04 / 明确上线边界',body:'候选库通过验证后，演示显式读取已批准的价格并应用到正式库。数据库 Clone、Data Branch 的 DIFF/MERGE 是不同操作；大表 CI 主线无需自动合并。'},
      {title:'05 / 扩展到 Data Branch',body:'官方教程还覆盖按表建分支、逐行 DIFF、MERGE、冲突处理和回滚。它们适合需要审查数据行变更的流程；本场景重点验证大表 Clone 与 CI 隔离。'},
    ],
    references:[
      ['Instant Clone for Multi-Team Development','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/efficient-clone-demo.html'],
      ['Git for Data: Data Branch Management','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/git4data-demo.html'],
      ['Git4Data 教程源码','https://github.com/matrixorigin/git4data-tutorial'],
    ],
  },
  vector: {
    definition:'向量检索把商品或文档表示为定长数值向量，SQL 用距离函数找出最接近查询向量的记录。MatrixOne 在业务表中保存向量列，并支持 IVF 索引、距离排序以及普通字段过滤。索引建好之后，还需要监测聚类中心的负载与查询效果。',
    essence:'从向量写入、索引构建、相似度查询到索引健康检查，形成完整的检索生命周期。',
    uses:[
      ['意图搜索','用户说“旅行充电”时，可按含义接近程度找到多个相关商品。'],
      ['相似商品','以一个商品或用户需求的向量为起点，取距离最近的 Top-K 结果。'],
      ['检索后加业务约束','按向量距离排序的同时保留库存、价格等业务字段。'],
      ['索引健康维护','监测每个 IVF 聚类中心的向量数量；数据分布变化后重新评估索引。'],
    ],
    sql:[
      {title:'建立向量列',why:'VECF32(4) 是本案例的四维样本；真实业务需使用与嵌入模型一致的维度。',code:'CREATE TABLE demo_shop_ci.ivf_health_docs (\n  id BIGINT PRIMARY KEY,\n  embedding VECF32(4)\n);'},
      {title:'先写入，再建 IVF 索引',why:'健康度案例先写入 1200 个预生成向量，再用 LISTS=16 建索引；商品检索案例另用 6 件商品和 LISTS=3。',code:"SELECT COUNT(*) AS vectors FROM demo_shop_ci.ivf_health_docs;\nCREATE INDEX idx_embedding_ivf USING IVFFLAT\nON demo_shop_ci.ivf_health_docs(embedding)\nLISTS=16 OP_TYPE 'vector_l2_ops';"},
      {title:'按距离查询 Top-K',why:'L2_DISTANCE 越小越接近；结果同时返回价格与库存。',code:"SELECT product_id, name, price, stock,\n       ROUND(L2_DISTANCE(embedding, '[0.95,0.08,0.02,0.00]'), 3) AS distance\nFROM demo_shop_ci.products\nWHERE stock > 0\nORDER BY L2_DISTANCE(embedding, '[0.95,0.08,0.02,0.00]')\nLIMIT 5;"},
      {title:'按查询调整扫描中心',why:'nprobe 决定本次 IVF 查询探测几个中心。扩大范围可能提高召回，也会改变扫描工作量；6 件商品仅验证语法和路径。',code:"SELECT product_id, name FROM demo_shop_ci.products\nORDER BY L2_DISTANCE(embedding,'[0.95,0.08,0.02,0.00]')\nLIMIT 5 BY RANK WITH OPTION 'nprobe=2';"},
      {title:'用 EXPLAIN 确认索引路径',why:'观察实际计划中的 ivf_search，而不把“建了索引”当成“查询一定用了索引”。4.2.4 中 pre 过滤需要 BY RANK WITH OPTION 语法。',code:"EXPLAIN SELECT product_id, name FROM demo_shop_ci.products\nWHERE stock>0\nORDER BY L2_DISTANCE(embedding,'[0.95,0.08,0.02,0.00]') LIMIT 5;\n-- 对照过滤模式\nEXPLAIN SELECT product_id, name FROM demo_shop_ci.products\nWHERE stock>0\nORDER BY L2_DISTANCE(embedding,'[0.95,0.08,0.02,0.00]')\nLIMIT 5 BY RANK WITH OPTION 'mode=pre';"},
      {title:'定位 IVF 内部索引表',why:'MatrixOne Python SDK 的 get_ivf_stats() 也从 mo_catalog 获取 entries 与 centroids 表名。',code:"SELECT i.algo_table_type, i.index_table_name\nFROM mo_catalog.mo_indexes i\nJOIN mo_catalog.mo_tables t ON i.table_id=t.rel_id\nWHERE t.reldatabase='demo_shop_ci'\n  AND t.relname='ivf_health_docs'\n  AND i.column_name='embedding' AND i.algo='ivfflat';"},
      {title:'检查中心负载并重建',why:'先统计每个聚类中心的向量数量，关注空中心和 max/min 负载比；REINDEX 可改变 LISTS 并重新训练。',code:'SELECT __mo_index_centroid_fk_id AS centroid_id, COUNT(*) AS vectors\nFROM demo_shop_ci.`<上一步查出的 entries 表>`\nGROUP BY __mo_index_centroid_fk_id ORDER BY centroid_id;\nALTER TABLE demo_shop_ci.ivf_health_docs\nALTER REINDEX idx_embedding_ivf IVFFLAT LISTS=32;'},
    ],
    deepDive:[
      {title:'01 / 理解 IVF 的分桶',body:'IVF 将向量分配到若干聚类中心。LISTS 决定分桶数量；每个中心的向量数反映负载分布。查询 Top-K 时需要权衡搜索范围、延迟和召回，不能仅凭建索引成功就认定检索质量。'},
      {title:'02 / 创建时机',body:'先导入有代表性的向量，再建 IVF 索引。若在空表或极少数据上训练，中心可能分布不佳；后续导入更多向量也不会自动修正最初的中心。本页健康度实验使用 1200 个预生成向量，而商品搜索仅有 6 个样本，不能用商品表评估生产索引健康。'},
      {title:'03 / 怎么判断健康度',body:'比较总向量数与索引 entries 数；观察聚类中心数、空中心数、每个中心的负载，以及最大/最小非空中心负载比。官方教程把负载比 2.0、2.5 作为示例观察阈值，实际决策还应结合数据分布、查询延迟和召回。'},
      {title:'04 / 数据变化后复查',body:'批量写入、删除或分布改变后重新检查。下方按钮在本地真实创建 1200 行索引样本，返回每个中心的行数；重建按钮执行 ALTER REINDEX LISTS=32，再次读取分布。重建后的负载比由实际结果决定。'},
      {title:'05 / HNSW 如何选择',body:'官方 HNSW 教程讲图索引、BIGINT 主键、m、ef_construction、ef_search 和查询延迟/召回权衡。它与 IVF 是两条索引路线；本次可执行案例选 IVF，并用健康度实验展示训练与维护。'},
      {title:'06 / 混合检索与应用接口',body:'官方 Hybrid Search 教程把向量距离、全文命中和普通 WHERE 条件组合，也包含 JOIN 模式。Pinecone 兼容接口和 RAG 教程展示应用层接入。本页 SQL 控制台聚焦同一商品表上的向量排序、库存过滤和全文查询，应用侧可在此基础上扩展。'},
    ],
    deepDiveTitle:'向量索引的完整生命周期',
    references:[
      ['IVF Index Health Monitoring','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/ivf-index-health-demo.html'],
      ['HNSW Vector Index','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/hnsw-vector-demo.html'],
      ['Hybrid Search','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/hybrid-search-demo.html'],
      ['Pinecone-Compatible Vector Search','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/pinecone-vector-demo.html'],
      ['MatrixOne 向量用户指南','https://github.com/XuPeng-SH/tae_design/blob/for_design/matrixone_vector_user_guide.md'],
    ],
  },
  fulltext: {
    definition:'全文检索为文本建立索引，让 SQL 能按词项搜索名称、描述或文档正文。MatrixOne 的 MATCH AGAINST 用于查询命中项；本演示还把 Stage 中的 DOCX 通过 DATALINK 接入检索。',
    essence:'结构化商品字段和非结构化说明书都能从 SQL 入口查到。',
    uses:[
      ['商品关键词搜索','当用户输入商品名或描述中明确出现的词时，直接返回命中商品。'],
      ['文档正文查找','客服可搜索说明书中的 warranty 等词，定位对应商品文档。'],
      ['与业务数据结合','命中结果仍保留商品 ID，可继续读取价格与库存。'],
    ],
    sql:[
      {title:'索引商品文本',why:'把商品名称和描述作为全文检索字段。',code:'CREATE FULLTEXT INDEX ft_products\nON demo_shop_ci.products(name, description);'},
      {title:'按关键词查商品',why:'MATCH AGAINST 同时作为过滤和相关度评分。',code:"SELECT product_id, name, price,\n       MATCH(name,description) AGAINST('charger' IN NATURAL LANGUAGE MODE) AS score\nFROM demo_shop_ci.products\nWHERE MATCH(name,description) AGAINST('charger' IN NATURAL LANGUAGE MODE)\nORDER BY score DESC;"},
      {title:'比较相关度算法',why:'本演示使用经典 FULLTEXT，其默认评分为 TF-IDF；在同一连接里 SET 为 BM25 后，可对相同查询重新计分。下方提供两条固定 SQL 实测。',code:"SET ft_relevancy_algorithm='BM25';\nSELECT product_id, MATCH(name,description)\n       AGAINST('charger' IN NATURAL LANGUAGE MODE) AS score\nFROM demo_shop_ci.products\nWHERE MATCH(name,description) AGAINST('charger' IN NATURAL LANGUAGE MODE)\nORDER BY score DESC;"},
      {title:'确认全文索引进入执行计划',why:'EXPLAIN 应显示 fulltext_index_scan；下方可直接在本地 v4.2.4 执行并检查原始计划。',code:"EXPLAIN SELECT product_id, name FROM demo_shop_ci.products\nWHERE MATCH(name,description) AGAINST('charger' IN NATURAL LANGUAGE MODE);"},
      {title:'查询说明书正文',why:'product_docs.manual 是指向 Stage 中 DOCX 的 DATALINK。',code:"SELECT product_id FROM demo_shop_ci.product_docs\nWHERE MATCH(manual) AGAINST('warranty');"},
      {title:'布尔检索',why:'使用 + 要求词项必须出现；适合明确的查询规则。',code:"SELECT product_id, name FROM demo_shop_ci.products\nWHERE MATCH(name,description) AGAINST('+charger' IN BOOLEAN MODE)\nORDER BY product_id LIMIT 8;"},
      {title:'JSON 内容检索',why:'WITH PARSER json 可以给 JSON 字段建立全文索引；下例是独立的建表示意。',code:"CREATE TABLE demo_shop_ci.product_specs (\n  product_id BIGINT PRIMARY KEY, details JSON\n);\nCREATE FULLTEXT INDEX ft_specs\nON demo_shop_ci.product_specs(details) WITH PARSER json;"},
    ],
    deepDiveTitle:'从索引到搜索体验的完整流程',
    deepDive:[
      {title:'01 / 选择索引内容',body:'商品名称与描述一起建立全文索引，说明书正文通过 Stage 中 DOCX 的 DATALINK 进入另一条全文路径。先决定搜索的是哪些字段和文件，而非先选择一个万能查询。'},
      {title:'02 / 自然语言模式',body:'MATCH AGAINST 在自然语言模式下检索相关词项并返回得分。页内控制台会给出真实命中行、名称、价格和得分；排序应检查业务上是否符合预期。'},
      {title:'03 / 布尔模式',body:'当用户或业务规则明确要求必须包含、排除或组合词项时，使用 IN BOOLEAN MODE。官方教程逐项介绍 +、-、词组等操作符；本案例提供 +charger 的可执行查询。'},
      {title:'04 / JSON 与非结构化文件',body:'JSON 全文索引需要选择 WITH PARSER json；DATALINK 路线索引的是 Stage 中文档内容。它们和普通文本索引是不同的数据入口，应分别验证命中结果。'},
      {title:'05 / 与向量组合',body:'官方 Hybrid Search 教程还讲全文 + 向量 + WHERE / JOIN 的组合。先分别验证两类召回，再在同一商品 ID 上合并和过滤，避免把关键词命中与语义相似度混为一谈。'},
    ],
    references:[
      ['Fulltext Natural Search','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/fulltext-natural-search-demo.html'],
      ['Fulltext Boolean Search','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/fulltext-boolean-search-demo.html'],
      ['Fulltext JSON Search','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/fulltext-json-search-demo.html'],
      ['Hybrid Search','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/hybrid-search-demo.html'],
      ['MatrixOne 全文检索用户指南','https://github.com/XuPeng-SH/tae_design/blob/for_design/matrixone_fulltext_user_guide.md'],
    ],
  },
  ingest: {
    definition:'供应商交来一个 CSV，数据库还没有商品行。先用 Stage 给文件目录起名；外表再把 CSV 的列映射为可查询的表。读取外表不会把商品导入业务库。质量问题另写进 quality_issues；最后才创建名为 demo_load_catalog 的 SQL Task，把符合规则的行插入 demo_shop.products。',
    essence:'文件位置、可查询映射、质量记录和正式入库，是四个独立动作；每一步都有自己的 SQL 和核对结果。',
    uses:[
      ['先验收文件','外表让开发者直接 SELECT 原始 CSV，先看列、行数和异常，再决定能否入库。'],
      ['保留坏数据证据','一行负价仍留在文件中，它的商品 ID 和原因被写入质量表。'],
      ['把规则变成具名作业','CREATE TASK 保存 INSERT ... SELECT 的规则；EXECUTE TASK 手动运行，运行状态和影响行数可以另查。'],
    ],
    sql:[
      {title:'00 准备两个演示库和目标表',why:'demo_ingest 放外表与质量记录；demo_shop 放业务商品、订单与文档引用。后面的 INSERT 需要这些目标表先存在。',code:'CREATE DATABASE demo_ingest;\nCREATE DATABASE demo_shop;\nCREATE TABLE demo_ingest.quality_issues(product_id BIGINT PRIMARY KEY,issue VARCHAR(80));\nCREATE TABLE demo_shop.products(\n  product_id BIGINT PRIMARY KEY,sku VARCHAR(40),name VARCHAR(120),\n  description TEXT,category VARCHAR(40),price DECIMAL(10,2),\n  stock INT,embedding VECF32(4));\nCREATE TABLE demo_shop.orders(\n  order_id BIGINT PRIMARY KEY,product_id BIGINT,qty INT,\n  amount DECIMAL(12,2),created_at DATETIME);\nCREATE TABLE demo_shop.product_docs(\n  doc_id BIGINT PRIMARY KEY,product_id BIGINT,manual DATALINK,\n  FULLTEXT(manual));'},
      {title:'01 给文件目录一个名字',why:'先切到 demo_ingest。demo_supplier 是 Stage 名称，指向实际 file:// 目录；CREATE STAGE 不会把 CSV 内容复制进业务表。',code:"USE demo_ingest;\nCREATE STAGE demo_supplier URL='file://<本地材料目录>/';\nSHOW STAGES;"},
      {title:'02 映射 CSV 的列和格式',why:'supplier_feed 是外表名。stage:// 引用刚创建的 Stage，products.csv 是目录中的文件；列类型和跳过首行的规则在这里定义。',code:"CREATE EXTERNAL TABLE demo_ingest.supplier_feed (\n  product_id BIGINT, sku VARCHAR(40), name VARCHAR(120),\n  description TEXT, category VARCHAR(40),\n  price DECIMAL(10,2), stock INT\n) INFILE{'filepath'='stage://demo_supplier/products.csv','format'='csv'}\nFIELDS TERMINATED BY ',' IGNORE 1 LINES;"},
      {title:'03 先查询原始文件',why:'SELECT 扫描外表对应的 CSV。本机返回 7 行；负价商品 #7 仍在原始文件中。',code:'SELECT product_id,name,price,stock\nFROM demo_ingest.supplier_feed ORDER BY product_id;\nSELECT product_id,price FROM demo_ingest.supplier_feed\nWHERE price<=0 OR stock<0;'},
      {title:'04 将异常写到质量表',why:'这一步是真正的持久写入，与外表读取不同。质量表记下商品 ID 和失败原因，原始 CSV 不会被改写。',code:"INSERT INTO demo_ingest.quality_issues\nSELECT product_id, 'price or stock is invalid'\nFROM demo_ingest.supplier_feed\nWHERE price<=0 OR stock<0;\nSELECT * FROM demo_ingest.quality_issues;"},
      {title:'05 创建 demo_load_catalog 任务',why:'先选择 demo_ingest 上下文，再用 CREATE TASK 声明任务名。任务体只导入有效且尚不存在的商品。DELIMITER 是 mysql 客户端处理 BEGIN 内分号的指令，不属于数据库任务体。',code:'USE demo_ingest;\nDELIMITER //\nCREATE TASK demo_load_catalog AS BEGIN\n  INSERT INTO demo_shop.products\n    (product_id,sku,name,description,category,price,stock)\n  SELECT f.product_id,f.sku,f.name,f.description,f.category,f.price,f.stock\n  FROM demo_ingest.supplier_feed f\n  WHERE f.price>0 AND f.stock>=0\n    AND NOT EXISTS (SELECT 1 FROM demo_shop.products p\n                    WHERE p.product_id=f.product_id);\nEND//\nDELIMITER ;'},
      {title:'06 手动执行并查运行记录',why:'EXECUTE TASK 触发已创建的具名任务；不能单凭命令返回就宣称入库成功。先查运行状态和 rows_affected。',code:'EXECUTE TASK demo_load_catalog;\nSHOW TASK RUNS FOR demo_load_catalog LIMIT 1;'},
      {title:'07 分别核对三处结果',why:'外表 7 行、质量表 1 行、业务表 6 行来自三个不同位置。NOT EXISTS 避免重复执行任务时重复插入相同商品。',code:'SELECT COUNT(*) FROM demo_ingest.supplier_feed;\nSELECT COUNT(*) FROM demo_ingest.quality_issues;\nSELECT COUNT(*) FROM demo_shop.products;'},
      {title:'08 为后续搜索补充向量与说明书',why:'这两类数据由演示脚本在 Task 完成后单独写入；不是 demo_load_catalog 的 SQL 体。六件商品各有预置四维向量。',code:"UPDATE demo_shop.products SET embedding='[0.98,0.06,0.02,0.00]' WHERE product_id=1;\nUPDATE demo_shop.products SET embedding='[0.88,0.15,0.03,0.00]' WHERE product_id=2;\nUPDATE demo_shop.products SET embedding='[0.05,0.95,0.05,0.00]' WHERE product_id=3;\nUPDATE demo_shop.products SET embedding='[0.10,0.05,0.95,0.00]' WHERE product_id=4;\nUPDATE demo_shop.products SET embedding='[0.02,0.02,0.05,0.98]' WHERE product_id=5;\nUPDATE demo_shop.products SET embedding='[0.89,0.09,0.02,0.00]' WHERE product_id=6;\nINSERT INTO demo_shop.product_docs VALUES\n  (1,1,'stage://demo_supplier/travel_charger.docx');"},
      {title:'09 另建百万行订单基线',why:'订单也不是 demo_load_catalog 导入的。本演示单独调用 generate_series 造出 100 万行，供大表 Clone 与 HTAP 使用。',code:"INSERT INTO demo_shop.orders\nSELECT result,1+(result%6),1,99.00,'2026-09-01 10:00:00'\nFROM generate_series(1,1000000) g;\nSELECT COUNT(*) FROM demo_shop.orders;"},
    ],
    deepDiveTitle:'把数据入口逐步拆开',
    deepDive:[
      {title:'01 / 文件先存在',body:'准备 7 行 products.csv 与一份 DOCX，文件放在 demo/runtime/fixtures。负价行故意保留；DOCX 后续由 DATALINK 进入全文检索。'},
      {title:'02 / Stage 只解决路径',body:'demo_supplier 给 file:// 目录命名，外表再用 stage://demo_supplier/products.csv 引用文件。Stage 不是商品表，也不负责质量校验。'},
      {title:'03 / 外表负责读取',body:'supplier_feed 定义七列、CSV 格式和忽略标题行。SELECT 外表得到 7 行原始数据，业务表此时仍为空。'},
      {title:'04 / 质量表记录异常',body:'一个 INSERT ... SELECT 把 price<=0 或 stock<0 的行写到 quality_issues，记录商品 ID 和错误原因；原始文件仍保留坏行。'},
      {title:'05 / 任务负责入库',body:'CREATE TASK demo_load_catalog 保存有效商品的 INSERT ... SELECT。EXECUTE TASK 手动触发，SHOW TASK RUNS 看状态和影响行数；NOT EXISTS 防止按同一 product_id 再次插入。'},
      {title:'06 / 搜索材料和大表是另两项动作',body:'任务完成后，脚本分别给六件商品写预置向量、把 Stage 中的 DOCX 作为 DATALINK 写入 product_docs，再用 generate_series 写 100 万行订单。这些不属于任务体。'},
    ],
    references:[['CREATE STAGE','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-stage.html'],['CREATE EXTERNAL TABLE','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-external-table.html'],['SQL Task','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/sql-task.html']],
  },
  htap: {
    definition:'HTAP 表示交易处理和分析查询共用同一套数据库。这里用一次下单事务写订单、扣库存，然后立即在同一份数据上做订单数和销售额汇总。',
    essence:'交易提交后的变化，可以由 SQL 分析查询直接读到。',
    uses:[
      ['实时运营看板','下单后立刻更新订单数和销售额，不等待批量同步。'],
      ['业务决策','运营查询可以直接依据刚发生的交易变化。'],
      ['简化数据链路','演示中的交易与汇总使用同一份订单表。'],
    ],
    sql:[
      {title:'事务内完成下单',why:'实际订单号、商品和金额由执行时决定。',code:'START TRANSACTION;\nUPDATE demo_shop.products SET stock=stock-1 WHERE product_id=1;\nINSERT INTO demo_shop.orders VALUES (<新订单号>, 1, 1, <成交金额>, CURRENT_TIMESTAMP());\nCOMMIT;'},
      {title:'立即读取分析结果',why:'这条聚合查询直接访问刚写入的订单表。',code:'SELECT COUNT(*) AS orders,\n       COALESCE(SUM(amount),0) AS revenue\nFROM demo_shop.orders;'},
      {title:'按商品分析实时销量',why:'从交易表做分组统计，形成比总数更接近运营看板的维度。',code:'SELECT product_id, COUNT(*) AS orders, SUM(amount) AS revenue\nFROM demo_shop.orders\nGROUP BY product_id ORDER BY revenue DESC;'},
    ],
    deepDiveTitle:'一次交易如何进入分析结果',
    deepDive:[
      {title:'01 / 建立交易基线',body:'记录下单前的订单数、销售额和目标商品库存，作为本次变化的比较基线。'},
      {title:'02 / 一次事务写两张表',body:'订单写入与库存扣减在同一事务中完成。执行脚本还会检查库存足够、生成新订单号，并在提交后返回订单明细。'},
      {title:'03 / 提交后即时聚合',body:'同一数据库直接执行 COUNT 与 SUM，核对订单数增加 1、销售额增加成交金额；实验台可继续下单观察变化。'},
      {title:'04 / 定时分析的扩展',body:'官方 HTAP 教程还展示风控规则和定时任务。这里选择即时经营汇总作为最容易核对的核心场景；定时分析可在此基础上扩展。'},
    ],
    references:[['HTAP Application Demo','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/htap-demo.html']],
  },
  recovery: {
    definition:'PITR（Point-in-Time Recovery，时间点恢复）让误删的表可以从事故前的历史状态找回。先创建策略，保留一个滚动时间窗口；误删后指定窗口内的时间戳恢复数据库或表。本章沿着这条事故路径执行，命名快照作为主动保存恢复基线的对照。',
    essence:'恢复需要先有受保护的历史，再选对时间点和对象范围，最后验证业务数据。',
    uses:[
      ['上线前留一个确定基线','升级前建立命名快照，验证失败时按快照回退。'],
      ['误改后按时间找回','批量 UPDATE 漏了 WHERE，可从 PITR 窗口中选择错误提交前的时刻。'],
      ['误删表后找回对象','本页先真实 DROP，再分别通过快照和数据库级 PITR 恢复。'],
      ['验证恢复质量','同样恢复六行，可能是六行正常价格，也可能是六行零价；必须逐列检查。'],
    ],
    sql:[
      {title:'PITR：预先开启保留窗口',why:'demo_price_history 是策略名，demo_pitr_shop 是恢复范围，1 h 是一小时滚动窗口。刚创建策略不会补回之前已丢失的历史。',code:"CREATE DATABASE demo_pitr_shop;\nCREATE PITR demo_price_history FOR DATABASE demo_pitr_shop RANGE 1 'h';\nSHOW PITR WHERE pitr_name='demo_price_history';"},
      {title:'PITR：准备价格并记录正常时间点',why:'复制六件商品到独立演练库。写入提交后等待跨过一秒，再读取服务器本地时间 T₁，确保它落在策略生效之后和误改之前。',code:'CREATE TABLE demo_pitr_shop.prices(\n  product_id BIGINT PRIMARY KEY,name VARCHAR(120),price DECIMAL(10,2));\nINSERT INTO demo_pitr_shop.prices\nSELECT product_id,name,price FROM demo_shop.products;\nSELECT product_id,name,price FROM demo_pitr_shop.prices ORDER BY product_id;\n-- 等待跨过秒边界后记录返回值为 T₁\nSELECT NOW();'},
      {title:'PITR：误改后再误删',why:'模拟 UPDATE 忘记 WHERE，六件商品都变成零价。等提交完成后记录 T₂，再删除表。T₁ 与 T₂ 都有六行，但业务含义完全不同。',code:'UPDATE demo_pitr_shop.prices SET price=0;\nSELECT product_id,name,price FROM demo_pitr_shop.prices ORDER BY product_id;\n-- 等待跨过秒边界后记录返回值为 T₂\nSELECT NOW();\n-- 再等到下一秒，模拟误删\nDROP TABLE demo_pitr_shop.prices;\nSELECT COUNT(*) FROM demo_pitr_shop.prices; -- 预期报错'},
      {title:'PITR：选择时间点并恢复整个演练库',why:'将占位符替换为 T₁ 或 T₂ 的秒级时间字符串。T₁ 恢复正常价格，T₂ 恢复零价。页面实验会代入实际记录的时间，并逐列比对。',code:"RESTORE DATABASE demo_pitr_shop\nFROM PITR demo_price_history '<YYYY-MM-DD HH:MM:SS>';\nSELECT product_id,name,price FROM demo_pitr_shop.prices ORDER BY product_id;"},
      {title:'管理保留窗口',why:'SHOW 查看策略范围；ALTER 改为两小时；DROP 删除保留策略。本演练保持一小时，管理语句供你理解生命周期。缩短窗口或删除策略会影响后续历史可用性。',code:"SHOW PITR WHERE pitr_name='demo_price_history';\nALTER PITR demo_price_history RANGE 2 'h';\n-- 演练结束且不再需要这些历史时\nDROP PITR demo_price_history;"},
      {title:'可选对照 · 快照：先准备报表与恢复基线',why:'promo_kpis 保存当前订单数。命名快照记录这一时刻的数据库状态。',code:'CREATE TABLE demo_shop.promo_kpis(metric VARCHAR(40) PRIMARY KEY,metric_value BIGINT);\nINSERT INTO demo_shop.promo_kpis SELECT \'orders\',COUNT(*) FROM demo_shop.orders;\nINSERT INTO demo_shop.promo_kpis SELECT \'products\',COUNT(*) FROM demo_shop.products;\nCREATE SNAPSHOT demo_before_accident FOR DATABASE demo_shop;'},
      {title:'可选对照 · 快照：删除、恢复、比较',why:'先查询确认表已不存在，再从命名快照恢复两项指标。',code:'DROP TABLE demo_shop.promo_kpis;\nSELECT COUNT(*) FROM demo_shop.promo_kpis; -- 预期报表不存在\nRESTORE TABLE demo_shop.promo_kpis{snapshot="demo_before_accident"};\nSELECT metric,metric_value FROM demo_shop.promo_kpis ORDER BY metric;'},
    ],
    deepDiveTitle:'从保护历史到验证恢复',
    deepDive:[
      {title:'01 / 先开启，再保护',body:'PITR 的可恢复区间受策略生效时间和滚动保留窗口共同约束。事故发生后才创建策略，不能追溯恢复事故前已丢失的历史。'},
      {title:'02 / 选择业务正确的时刻',body:'命令成功只表示还原了所选时刻。选在错误 UPDATE 之后，仍然会恢复零价。下方实验允许切换两个真实时间点，对比恢复后的六行价格。'},
      {title:'03 / 明确恢复范围',body:'本实验用 RESTORE DATABASE 恢复独立的 demo_pitr_shop；整个库在所选时间之后的变化都会回退。表级语法可指定 TABLE，账号与集群级恢复需按对应权限和策略范围使用。'},
      {title:'04 / 时间与精度',body:'本机 v4.2.4 将恢复字符串按服务器本地时区解析，格式为 YYYY-MM-DD HH:MM:SS。实验从数据库读时间，并为策略创建、提交、时间记录和后续修改留出秒级间隔。'},
      {title:'05 / 历史保留不是异地备份',body:'PITR 面向所保留历史内的逻辑误操作恢复。故障域外的数据副本、备份与恢复验证仍需单独规划；窗口越长，历史数据保留成本也需评估。'},
    ],
    references:[['RESTORE FROM PITR','https://docs.matrixorigin.cn/mo/en/v26.4.1.4/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/restore-pitr.html'],['CREATE PITR','https://docs.matrixorigin.cn/mo/zh/latest/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-pitr.html'],['快照回滚教程','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Tutorial/snapshot-rollback-demo.html']],
  },
  pubsub: {
    definition:'Publish/Subscribe 允许发布账号定义要共享的数据库对象，订阅账号在自己的数据库入口下读取这些数据。本演示发布商品表，合作伙伴账号订阅并查询。',
    essence:'共享由发布范围和账号决定；核对查询真正使用订阅账号。',
    uses:[
      ['合作伙伴目录','只开放商品目录给合作伙伴读取。'],
      ['跨账号协作','不同团队按账号边界访问同一份发布数据。'],
      ['减少手工导出','消费者通过订阅数据库查询，不必依赖定期 CSV 导出。'],
    ],
    sql:[
      {title:'发布商品表',why:'指定数据库、表和可订阅的目标账号。',code:'CREATE PUBLICATION demo_catalog\nDATABASE demo_shop TABLE products\nACCOUNT demo_partner;'},
      {title:'订阅账号创建入口',why:'以下语句在 demo_partner:admin 会话中执行。',code:'CREATE DATABASE partner_catalog\nFROM sys PUBLICATION demo_catalog;'},
      {title:'订阅端查询',why:'结果由合作伙伴账号读出。',code:'SELECT COUNT(*) AS products\nFROM partner_catalog.products;'},
    ],
    deepDiveTitle:'跨账号共享的完整路径',
    deepDive:[
      {title:'01 / 确定共享范围',body:'发布方只选择商品表，不把订单和内部质量表一起发布。发布权限以目标账号为边界。'},
      {title:'02 / 创建订阅入口',body:'合作伙伴在自己的账号下创建订阅数据库。页面上的核对查询真正用 demo_partner:admin 登录执行。'},
      {title:'03 / 验证可见内容',body:'订阅端按商品 ID 查询商品名和价格，核对 6 件商品与发布方目录对应。数据来源和执行账号会在控制台结果区显示。'},
      {title:'04 / 生命周期',body:'发布内容或账号发生变化时，需要重新审查发布范围与订阅入口；演示环境在重置时清理临时账号和 Publication。'},
    ],
    references:[['Publish-Subscribe','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Develop/Publish-Subscribe/pub-sub-overview.html']],
  },
  iceberg: {
    definition:'Iceberg 是开放的表格式：把对象存储中的数据文件、列定义、文件清单和快照组织成一张可查询、可演进的表。Parquet 保存列式数据，Iceberg 描述哪些文件属于哪个表状态；Catalog 根据表名找到元数据；MatrixOne 负责执行 SQL。本章从一张不存在的订单湖表开始，逐步把这些部件连接起来。',
    essence:'先建立湖表，再建立 SQL 入口；一次写入生成新的数据文件和表状态，查询沿着元数据找到该读的数据。',
    uses:[
      ['直接访问已有数据湖','订单归档已经由兼容引擎写入 Iceberg 时，可以把湖表映射到 MatrixOne，使用 SQL 查询。接入前要确认 Catalog、存储和访问权限。'],
      ['通过 SQL 追加湖表数据','本地演示启用 Iceberg 写入，通过 MatrixOne INSERT 追加订单，观察对象文件和 snapshot ID 如何变化。'],
      ['核对历史批次','保留追加前的 Catalog 分支，比较新旧两个表状态，定位多出来的订单。历史读取依赖相应快照和文件仍被保留。'],
    ],
    sql:[
      {title:'前提：本地服务已启用 Iceberg 读写',kind:'CN TOML 配置',why:'本演示的 v4.2.4 启动配置已包含这些开关。Catalog 注册、访问策略、外表映射和实际写入是后续独立步骤；只创建 Catalog 名称并不等于能读写。',code:'[cn.frontend.iceberg]\nenable = true\nenable-write = true'},
      ...ICEBERG_STAGES.map((stage,index)=>({title:String(index+1).padStart(2,'0')+' '+stage.title,kind:stage.kind,why:stage.explain+' '+stage.observe,code:stage.code(null)})),
    ],
    deepDiveTitle:'从文件到版本化湖表',
    deepDive:[
      {title:'01 / 四个角色',body:'MinIO 是存储，Nessie 是 Catalog，Iceberg 是表格式，MatrixOne 是计算引擎。把四者都叫“数据库”会掩盖表在哪里、谁负责找文件以及谁负责执行 SQL。'},
      {title:'02 / 两次建表各做什么',body:'REST CreateTable 在湖上创建 schema 和元数据；MatrixOne CREATE EXTERNAL TABLE 创建本地映射。demo_story_lake 是本地数据库，demo_lake_开头的是湖上 namespace，它们通过映射参数连接。'},
      {title:'03 / 写入才产生可读状态',body:'本地 v4.2.4 读尚无快照的新湖表会报告 snapshot ref not found。首次 INSERT 写四行并提交快照后，SELECT 才能读到四行。页面保留这个真实边界，避免把映射成功当成数据已经就绪。'},
      {title:'04 / 元数据怎样找到数据',body:'Catalog 指向 metadata JSON；表快照指向 manifest list，manifest 描述数据文件。Parquet 承载订单字段。页面列出实际 JSON、Avro 和 Parquet 路径，但目录内保留文件不等于查询必读文件。'},
      {title:'05 / 三种名字不要混淆',body:'append_orders_old 是本地外表别名，Nessie 分支是 Catalog 的版本引用，snapshot ID 是 Iceberg 表快照编号。第二张外表仍指向同一湖上表，只是使用另一 Catalog 分支。'},
      {title:'06 / 使用边界',body:'本例是未分区的 v2 湖表，使用 append_only 读写；bucket 只是普通列。分区裁剪、schema 演进、删除文件、维护和跨引擎并发是进一步主题，本例的五行对照不能作为这些能力或性能的证明。'},
    ],
    references:[['Apache Iceberg：术语与元数据关系','https://iceberg.apache.org/terms/'],['MatrixOne CREATE ICEBERG CATALOG','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-iceberg-catalog.html'],['Iceberg REST Catalog 协议','https://iceberg.apache.org/docs/nightly/rest-protocol/']],
  },
  cdc: {
    definition:'CDC 持续读取数据库的增量变更，并交付到目标系统。这里把 MatrixOne 的新订单同步到独立 MySQL，再按同一订单号在源端和目标端核对。',
    essence:'验证的是一条真实新订单从源端写入到目标端可见的全过程。',
    uses:[
      ['下游系统同步','把新增订单持续提供给另一个业务系统。'],
      ['增量数据交付','只关注新变更，而不是每次重导整张订单表。'],
      ['可核对复制结果','按订单号在两端查询，明确知道数据是否到达。'],
    ],
    sql:[
      {title:'准备变更保留窗口',why:'本地案例为 CDC 创建 PITR 配置。',code:"CREATE PITR demo_cdc_pitr\nFOR DATABASE demo_shop RANGE 3 'h';"},
      {title:'创建增量任务',why:'连接 URI 在实际执行时由本地服务填写；此处仅展示 SQL 结构。',code:"CREATE CDC demo_orders_cdc\n  '<MatrixOne 连接 URI>' 'mysql' '<MySQL 连接 URI>'\n  'demo_shop.orders:demo_sink.orders'\n  {'Level'='table','NoFull'='true'};"},
      {title:'核对同一新订单',why:'第二条查询连接独立 MySQL 目标端执行。',code:'SELECT COUNT(*) FROM demo_shop.orders WHERE order_id=<新订单号>;\nSELECT COUNT(*) FROM demo_sink.orders WHERE order_id=<新订单号>;' },
    ],
    deepDiveTitle:'一条增量变更如何到达下游',
    deepDive:[
      {title:'01 / 准备源与目标',body:'源端是 MatrixOne demo_shop.orders，目标端是独立 MySQL demo_sink.orders。先准备目标库和源端 PITR 窗口。'},
      {title:'02 / 建立 CDC 任务',body:'CREATE CDC 声明源、目标、表映射和 NoFull=true。演示等待任务到达初始检查点，之后才写入新的订单。'},
      {title:'03 / 产生增量',body:'在 MatrixOne 事务中插入新订单并记录订单号；这一步发生在 CDC 已运行之后，符合“只同步后续变化”的设置。'},
      {title:'04 / 两端按主键核对',body:'循环等待目标可见，然后在 MatrixOne 和 MySQL 分别查询同一订单号。两个控制台单元会明确标出当前连接的数据源。'},
      {title:'05 / 观察任务状态',body:'除了行级核对，还应查看 SHOW CDC ALL 或具体任务状态；数据到达与任务健康是两个不同的观察点。'},
    ],
    references:[['CDC: MatrixOne to MySQL','https://docs.matrixorigin.cn/mo/en/latest/MatrixOne/Maintain/cdc/mo-mysql.html']],
  },
};
