import {renderIcebergLesson,wireIcebergLesson} from './iceberg.js';
import {renderPitrLab,wirePitrLab} from './pitr.js';
import {ACTS,STEPS,STORY,CHECKS,getCapability,nextIncomplete} from './catalog.js';
import {FEATURE_CONTENT} from './content.js';
import {renderIngestLesson} from './ingest-chapters.js';
import {renderStepExplainer} from './step-explainers.js';
import {$,h,api,shell,updateProgress,metricTiles,animateMetrics,sqlBlock,wireCopy,checkCell,wireChecks,stepHref,capHref,done,toast} from './common.js';

shell('demo');
let state,connectionError=null;
try {state=await api('state');} catch(error) {connectionError=error.message;state={completed:[],metrics:{},evidence:[],events:[]};}
let selected=new URLSearchParams(location.search).get('step');
if(!STEPS.some(step=>step.id===selected))selected=nextIncomplete(state)?.id||'start';

function chapterLinks(){
  return ACTS.map((act,index)=>`<div class="docs-nav-group"><div class="docs-nav-heading"><span>${h(act.number)}</span>${h(act.title)}</div>${STEPS.filter(step=>step.act===index).map(step=>`<a href="${stepHref(step.id)}" class="docs-nav-item ${step.id===selected?'current':''} ${done(state,step.id)?'done':''}"><span class="nav-status">${done(state,step.id)?'✓':String(STEPS.indexOf(step)+1).padStart(2,'0')}</span>${h(step.title)}</a>`).join('')}</div>`).join('');
}

function startMethods(){
  return `<div class="docs-methods"><details open><summary><strong>两条命令，从环境到演示</strong><span>Debian / Ubuntu</span></summary><p>在仓库根目录执行。安装器准备 Python、SQL 客户端、构建工具、Docker 和固定 release 源码；启动器预检后构建数据库并打开网页服务。</p><pre><code>./demo/setup.sh
./demo/start.sh</code></pre><p>首次下载和编译需要时间；再次启动复用已有产物。无需 Node.js 或 npm。</p><button id="check-environment" class="btn">检查本机环境</button><div id="environment-result" aria-live="polite"></div></details><details open><summary><strong>源码构建 · 本演示选择</strong><span>v4.2.4 / 16042</span></summary><p>从本机 MatrixOne 仓库准备固定 release 工作区，构建 mo-service，生成独立配置并启动。运行后执行 <code>SELECT VERSION()</code> 核对版本。</p></details><details><summary><strong>Docker standalone</strong><span>快速试用</span></summary><p>容器适合快速体验。镜像标签需要单独指定；本演示使用固定 v4.2.4 release，避免把其他版本的行为混进结果。</p></details><details><summary><strong>mo_ctl</strong><span>安装与运维</span></summary><p>提供安装、升级、备份及健康检查入口，适合需要长期运行和生命周期管理的环境。</p></details></div>`;
}

function render(){
  updateProgress(state);
  const index=STEPS.findIndex(step=>step.id===selected),step=STEPS[index],chapter=ACTS[step.act],story=STORY[step.id],cap=getCapability(step.capability),feature=FEATURE_CONTENT[step.capability];
  const next=nextIncomplete(state),isDone=done(state,step.id),canRun=!connectionError&&next?.id===step.id;
  const runLabel=step.id==='schema'?'创建 Stage、外表并核对':step.id==='ingest'?'创建并运行 SQL Task':'执行本章操作';
  const featureTitle=step.id==='schema'?'Stage 和外表各负责什么':step.id==='ingest'?'demo_load_catalog 是什么':step.id==='start'?'运行环境':step.id==='prepare'?'演示材料':step.id==='search'?'本章使用的检索能力':'本章使用的能力';
  const featureIntro=step.id==='schema'?'这一步只建立文件访问路径，并把异常行记入质量表。Stage 给目录命名，外表定义 CSV 的解析方式；两者都不会自动将商品导入业务库。':step.id==='ingest'?'上一章已经从外表查到七行原始数据，并留下负价问题。现在创建 demo_load_catalog 任务，把有效商品导入业务表；任务运行史与订单造数分别核对。':step.id==='start'?'MatrixOne v4.2.4 是本教程所有 SQL 的执行环境。这里从源码构建本地服务，再用 SELECT VERSION() 核对实际版本。':step.id==='prepare'?'供应商文件是 Stage 与外表能力的输入。演示保留一条负价数据，让质量检查和 ETL 有真实对象。':feature.definition;
  const proofs=(state.evidence||[]).filter(item=>item.step===step.id);
  const operationProof=[...proofs].reverse().find(item=>!item.result?.includes('row(s)'));
  const checks=CHECKS[step.id]||[];
  const status=connectionError?`<div class="docs-connection error"><span class="status-dot"></span><span>${h(connectionError)}</span></div>`:`<div class="docs-connection"><span class="status-dot is-live"></span><span>本地执行服务已连接 · ${done(state,'start')?'MatrixOne v4.2.4 已启动':'数据库待启动'}</span><span class="micro">127.0.0.1:8042 → 16042</span></div>`;
  $('#app').innerHTML=`<div class="docs-layout"><aside class="docs-sidebar"><a class="docs-sidebar-brand" href="/">MATRIXONE / 场景演示</a><p>先懂功能，再看它如何用于场景</p><div class="docs-progress"><i style="width:${Math.round((state.completed||[]).length/STEPS.length*100)}%"></i></div>${chapterLinks()}</aside><article class="docs-article"><div class="docs-breadcrumb"><a href="/">功能目录</a><span>/</span>${h(chapter.title)}<span>/</span>${String(index+1).padStart(2,'0')}</div><details class="docs-mobile-nav"><summary>章节目录 · ${String(index+1).padStart(2,'0')} / 13</summary>${chapterLinks()}</details>${status}<header class="docs-article-header"><div class="eyebrow">Scenario ${String(index+1).padStart(2,'0')} / ${h(chapter.title)}</div><h1>${h(step.title)}</h1><p class="docs-lede">${h(step.id==='start'?'先建立固定版本的运行环境，后续所有功能和 SQL 才有可核对的基础。':step.id==='prepare'?'先准备供应商交来的 CSV 和 DOCX，后续用 Stage、外表和 SQL Task 处理。':story.scene)}</p></header>
  <section class="docs-section" id="feature"><div class="docs-section-number">01 / FEATURE</div><h2>${h(featureTitle)}</h2><p>${h(featureIntro)}</p>${step.id==='search'?`<p>${h(FEATURE_CONTENT.fulltext.definition)}</p>`:''}<p class="docs-context-link">${step.id==='start'?'下面列出其他启动方式；本演示执行源码构建。':`先阅读 <a href="${capHref(cap.id)}">「${h(cap.title)}」功能文档 ↗</a>${step.id==='search'?` 与 <a href="${capHref('fulltext')}">「全文检索」功能文档 ↗</a>`:''}`}</p>${step.id==='start'?startMethods():''}${renderIngestLesson(step.id,state)}${renderStepExplainer(step.id)}${step.id==='iceberg'?renderIcebergLesson(state):''}</section>
  <section class="docs-section" id="key-sql"><div class="docs-section-number">02 / SQL</div><h2>关键 SQL</h2><p>${h(step.id==='prepare'?'这一章准备本地文件；下一章开始用 Stage 和外表 SQL 读取。':step.id==='schema'?'按顺序读：创建两个演示库与目标表，Stage 命名目录，外表解析 CSV，然后明确执行 INSERT 记录异常。实际运行会先重建演示专用对象，并填写本机目录路径。':step.id==='ingest'?'按顺序读：CREATE TASK 定义 demo_load_catalog，EXECUTE TASK 触发，SHOW TASK RUNS 查结果；后面的向量、DOCX 引用和订单写入都在任务体之外。':`这些 SQL 用于：${step.action}。具体参数与执行结果以本机记录为准。`)}</p>${sqlBlock(step.sql,step.id==='prepare'?'材料操作':'本章 SQL 预览')}</section>
  <section class="docs-section" id="context"><div class="docs-section-number">03 / SCENARIO</div><h2>场景：这一章何时需要它</h2><p>${h(story.body)}</p><div class="docs-callout"><strong>本章目标</strong><span>${h(step.expected)}</span></div></section>
  <section class="docs-section" id="execute"><div class="docs-section-number">04 / EXECUTE</div><h2>${step.id==='prepare'?'准备演示材料':'在本地执行'}</h2><p>${h(step.action)}</p><div class="execution-cell"><div class="execution-cell-top"><span><i class="code-dot"></i>${step.id==='prepare'?'材料准备':'操作执行'}</span><span>${h(step.id==='start'?'本地服务 + SQL':'MatrixOne v4.2.4')}</span></div><div class="execution-cell-bottom">${isDone?`<div class="execution-state success">✓ 本章已执行，结果来自本机数据库</div>`:`<button id="run-step" class="btn primary" ${canRun?'':'disabled'}>${step.id==='start'?'一键启动并核对版本':step.id==='prepare'?'生成材料':runLabel} <span>▶</span></button>`}<span id="run-status" class="run-status">${isDone?'完成':connectionError?'执行服务未连接':canRun?'准备就绪':`请先完成第 ${STEPS.indexOf(next)+1} 章`}</span></div></div>${!isDone&&!canRun&&!connectionError?`<p class="docs-hint"><a href="${stepHref(next.id)}">从当前可执行章节开始 →</a></p>`:''}${step.id==='prepare'?'<p class="docs-hint">这一章生成 CSV 与 DOCX 文件，没有数据库 SQL；下一章才用 Stage 读取。</p>':''}</section>
  <section class="docs-section" id="result"><div class="docs-section-number">05 / RESULT</div><h2>看数据库返回什么</h2><p>指标由本次操作后查询得到。下方控制台可以重新从数据库取结果。</p><div class="docs-result-card">${metricTiles(step.keys,state)}<div class="result-line ${isDone?'':'pending'}">${isDone?h(operationProof?.result||state.events?.filter(item=>item.step===step.id).at(-1)?.detail||'本章已完成'):'尚未执行；不会显示预设的假结果。'}</div></div>${proofs.length?`<details class="docs-proof"><summary>查看本章已执行的关键 SQL 与核对记录 <span>${proofs.length} 条</span></summary>${proofs.map((item,i)=>`<div class="docs-proof-entry">${sqlBlock(item.sql,`执行记录 ${i+1}`)}<p>${h(item.result)}</p></div>`).join('')}</details>`:''}</section>
  <section class="docs-section" id="verify"><div class="docs-section-number">06 / VERIFY</div><h2>在控制台重新查询</h2><p>${checks.length?'查询真正访问本地数据库，并显示结果表格和耗时。普通 MatrixOne 查询可以直接编辑。':'本章只准备本地文件。到下一章可以用 SQL 查询 Stage 与外表。'}</p>${checks.map(check=>checkCell(check,isDone&&!connectionError)).join('')}</section>
  ${step.id==='recover'?renderPitrLab(state):''}<section class="docs-next" id="next"><span class="eyebrow">接下来</span><p>${h(story.next)}</p><div class="action-row"><a class="btn primary" href="${index<STEPS.length-1?stepHref(STEPS[index+1].id):'/lab.html?tab=sql'}">${index<STEPS.length-1?`阅读第 ${index+2} 章`:'打开 SQL 控制台'} →</a><a class="text-link" href="/evidence.html?step=${encodeURIComponent(step.id)}">查看本章 SQL 证据 ↗</a></div></section>${(state.completed||[]).length?'<button id="reset-demo" class="docs-reset">↺ 从头演示</button>':''}</article><aside class="docs-toc"><strong>本页内容</strong><a href="#feature">功能与用途</a><a href="#key-sql">关键 SQL</a><a href="#context">场景叙事</a><a href="#execute">执行操作</a><a href="#result">数据库结果</a><a href="#verify">控制台查询</a>${step.id==='recover'?'<a href="#pitr-lab">PITR 时间点实验</a>':''}<div class="docs-toc-rule"></div><span>${(state.completed||[]).length} / 13 已完成</span></aside></div>`;
  const operationCell=$('.execution-cell');
  operationCell.outerHTML=`<div class="db-console operation-console"><div class="db-console-top"><div class="db-console-title"><span class="console-window-dots"><i></i><i></i><i></i></span><strong>${h(step.id==='prepare'?'材料准备':step.title)}</strong></div><span class="db-connection"><i class="status-dot ${done(state,'start')?'is-live':''}"></i>${h(step.id==='prepare'?'本地文件':step.id==='start'?'本地服务 + SQL':'MatrixOne v4.2.4')}</span></div><div class="db-console-tabs"><span class="active">操作 SQL</span><span class="db-console-context">场景章节 · 按顺序执行</span></div><div class="db-editor"><div class="db-gutter">${step.sql.split('\n').map((_,line)=>`<span>${line+1}</span>`).join('')}</div><textarea class="db-sql-input" aria-label="本章 SQL 预览" spellcheck="false" readonly>${h(step.sql)}</textarea></div><div class="db-console-toolbar">${isDone?'<span class="execution-state success">✓ 本章已执行</span>':`<button id="run-step" class="btn primary" ${canRun?'':'disabled'}>${step.id==='start'?'▶ 一键启动并核对版本':step.id==='prepare'?'▶ 生成材料':`▶ ${runLabel}`}</button>`}<span id="run-status" class="check-state">${isDone?'查询与操作完成':connectionError?'执行服务未连接':canRun?'就绪':`请先完成第 ${STEPS.indexOf(next)+1} 章`}</span></div><div class="db-results"><div class="db-result-tabs"><span class="active">结果</span><span>消息</span></div><div class="db-operation-result">${isDone?h(operationProof?.result||'操作已完成，详细指标见下方。'):'执行后显示本机返回结果和指标。'}</div></div><div class="db-console-foot"><span>LOCAL OPERATION</span><span>${h(step.id==='prepare'?'文件步骤':'执行记录可回看')}</span></div></div>`;
  wireCopy();wireIcebergLesson($('#app'),state);wirePitrLab($('#app'),state);wireChecks($('#app'));animateMetrics($('#app'));
  $('#run-step')?.addEventListener('click',run);
  $('#check-environment')?.addEventListener('click',async()=>{const button=$('#check-environment');button.disabled=true;$('#environment-result').textContent='正在检查工具链与 Docker…';try{const result=await api('environment');$('#environment-result').innerHTML=`<p>${result.ok?'✓ 环境就绪':'有依赖未就绪，请运行 ./demo/setup.sh'}</p><ul>${result.checks.map(c=>`<li><strong>${c.ok?'✓':'✗'} ${h(c.name)}</strong> · ${h(c.detail)}</li>`).join('')}</ul><p>${h(result.notes.join(' '))}</p>`;}catch(e){$('#environment-result').textContent=e.message;}finally{button.disabled=false;}});
  $('#reset-demo')?.addEventListener('click',async()=>{if(!confirm('重置将删除 demo_shop、demo_shop_ci、demo_ingest、demo_pitr_shop、demo_story_lake，以及演示任务、快照、PITR、订阅账号、CDC 目标数据和网页进度。依赖和编译产物保留；Iceberg 湖端历史保留，下轮使用新的命名空间。继续吗？'))return;const button=$('#reset-demo');button.disabled=true;button.textContent='正在重置…';try{state=await api('reset',{confirm:'reset-demo'});selected='start';history.replaceState(null,'',stepHref(selected));render();toast('演示数据与进度已清理并核对，可以从头演示','ok');window.scrollTo(0,0);}catch(error){button.disabled=false;button.textContent='↺ 从头演示';toast(error.message);}});
}

async function run(){
  const button=$('#run-step'),status=$('#run-status'),started=Date.now(),lastId=state.events?.at(-1)?.id||0;
  button.disabled=true;button.textContent='正在执行…';status.className='run-status running';
  const ticker=setInterval(async()=>{const seconds=Math.floor((Date.now()-started)/1000);try{const progress=await api('state');const event=[...(progress.events||[])].reverse().find(item=>item.id>lastId);status.textContent=event?`${event.title} · ${seconds}s`:`正在连接与执行 · ${seconds}s`;}catch{status.textContent=`执行中 · ${seconds}s`;}},1200);
  try{state=await api('step',{step:selected});clearInterval(ticker);render();toast('操作完成。现在可以逐条运行核对 SQL。','ok');}
  catch(error){clearInterval(ticker);button.disabled=false;button.textContent='重试本章操作 ▶';status.className='run-status error';status.textContent=error.message;toast(error.message);}
}

render();
