import {ACTS,CAPABILITIES,STEPS} from './catalog.js';
import {$,h,api,shell,updateProgress,capHref,stepHref} from './common.js';

shell('home');
const featured=CAPABILITIES.slice(0,3),support=CAPABILITIES.slice(3);
$('#app').innerHTML=`<section class="doc-home-hero"><div class="doc-home-copy"><div class="eyebrow">MatrixOne / Feature Documentation</div><h1>MatrixOne<br><em>功能指南。</em></h1><p>从开发者关心的问题出发，逐项说明九项重点功能：功能介绍、关键细节、SQL 解释和真实操作连成一条阅读路径。每项能力都有独立案例：从准备数据到实际执行、验收与重置。</p><div class="hero-actions"><a class="btn primary" href="#core">浏览功能目录 ↓</a><a class="btn ghost" href="${capHref('git4data')}">先读 Git for Data →</a></div><div class="doc-home-meta"><span>VERSION <strong>v4.2.4</strong></span><span>FEATURES <strong>09</strong></span><span>SCENARIO STEPS <strong>13</strong></span></div></div><aside class="home-launch-card"><div class="home-launch-top"><span class="code-dot"></span> LOCAL SQL CONNECTION <span>v4.2.4</span></div><p>首次安装环境，再一键启动数据库与文档。先读功能介绍，在同一页从零执行完整案例并重置；也可以沿主线场景串联所有能力。</p><div class="home-launch-code">$ ./demo/setup.sh<br>$ ./demo/start.sh</div><div id="home-service" class="home-launch-status"><i></i>正在检测本地服务…</div><div class="home-launch-links"><a href="${stepHref('start')}">体验贯穿场景 →</a><a href="/lab.html?tab=sql">打开 SQL 控制台 ↗</a></div></aside></section>
<section class="home-reading-path"><div><span>01 / DEFINITION</span><strong>是什么</strong><p>说明能力是什么、解决什么问题。</p></div><div><span>02 / DETAILS</span><strong>细节补充</strong><p>拆开关键对象、操作顺序与边界。</p></div><div><span>03 / SQL</span><strong>SQL 解释</strong><p>逐条理解语句，再执行真实查询。</p></div><div><span>04 / EXECUTE</span><strong>完整案例与验收</strong><p>在本页从零操作、查看结果，并单独重置。</p></div></section>
<section id="core" class="section"><div class="section-head"><div><div class="eyebrow">01 / 重点功能</div><h2>先看这三项</h2></div><p>每篇独立说明定义、用途、关键 SQL，再进入场景。查询区连接本地数据库，返回真实行数与结果。</p></div><div class="feature-grid">${featured.map(item=>`<a class="feature-card ${item.tone}" href="${capHref(item.id)}"><span class="number">${h(item.tag)}</span><h3>${h(item.title)}</h3><p>${h(item.summary)}</p><span class="arrow">打开功能文档 ↗</span></a>`).join('')}</div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">02 / 更多功能</div><h2>完整的数据路径</h2></div><p>从外部文件进入数据库，再走向实时业务、跨账号共享、湖表和其他系统。</p></div><div class="support-grid">${support.map(item=>`<a class="support-card" href="${capHref(item.id)}"><span class="small-tag">${h(item.tag)}</span><h3>${h(item.title)} <span class="teal">↗</span></h3><p>${h(item.subtitle)}</p></a>`).join('')}</div></section>
<div class="soft-rule"></div><section><div class="section-head"><div><div class="eyebrow">03 / 场景演示</div><h2>一场大促，串起所有操作</h2></div><p>供应商送来有瑕疵的商品数据。工程师在百万行订单上验证搜索升级，处理交易与误删事故，最后共享并同步数据。故事帮助理解功能使用的时机。</p></div><div class="journey">${ACTS.map((act,i)=>`<a href="${stepHref(STEPS.find(step=>step.act===i).id)}"><strong>${h(act.number)} / ${h(act.range)}</strong><h3>${h(act.title)} →</h3><p>${h(act.line)}</p></a>`).join('')}</div><div class="hero-actions" style="margin-top:36px"><a class="btn primary" href="${stepHref('start')}">打开场景演示 →</a><a class="text-link" href="/lab.html?tab=sql">打开 SQL 控制台 ↗</a></div></section>`;
api('state').then(state=>{updateProgress(state);$('#home-service').innerHTML=`<i class="is-live"></i>本地执行服务已连接 · ${(state.completed||[]).length}/13 章已完成`;}).catch(error=>{$('#home-service').textContent=error.message;$('#home-service').classList.add('error');});
