import {caseSQL,caseId,h,done,api,sqlBlock,resultTable,wireCopy} from './common.js';
import {ICEBERG_STAGES,ICEBERG_ROLES} from './iceberg-content.js';
function view(data,ready,selected,role,busy){
  const completed=data?.completed||[],next=ICEBERG_STAGES.findIndex(s=>!completed.includes(s.id));
  const stage=ICEBERG_STAGES[selected],record=data?.records.find(r=>r.phase===stage.id);
  const meta=data?.metadata,files=data?.objects||[],first=new Set((data?.first_objects||[]).map(r=>r[0]));
  return `<div class="lake-heading"><span class="guide-mini-label">ICEBERG / 从零建立一张湖表</span><h3>先认识表在哪里，再让 SQL 找到它</h3><p>本例是一张开放格式的订单归档表。沿着六步走，你会亲手建立外部服务、湖表和 SQL 映射，再看到写入产生文件与快照。</p></div>
  <div class="lake-roles">${ICEBERG_ROLES.map(([name],i)=>`<button data-lake-role="${i}" aria-pressed="${i===role}"><small>0${i+1}</small><strong>${h(name)}</strong><span>${i===0?'执行 SQL':i===1?'定位表元数据':i===2?'描述表和版本':'保存实际文件'}</span></button>`).join('')}</div><p class="lake-role-detail">${h(ICEBERG_ROLES[role][1])}</p>
  <div class="lake-workbench"><nav class="lake-steps" aria-label="Iceberg 建表步骤">${ICEBERG_STAGES.map((s,i)=>`<button data-lake-step="${i}" aria-pressed="${i===selected}"><span>${completed.includes(s.id)?'✓':String(i+1).padStart(2,'0')}</span>${h(s.title)}</button>`).join('')}</nav><div class="lake-stage"><span class="guide-mini-label">步骤 ${selected+1} / ${h(stage.kind)}</span><h4>${h(stage.title)}</h4><p>${h(stage.explain)}</p><p class="lake-expect"><strong>核对什么</strong>${h(stage.observe)}</p>${sqlBlock(record?.code||stage.code(data),record?'本步实际执行记录':stage.kind+' · 执行前预览')}<div class="lake-actions"><button class="btn primary" data-lake-action="${stage.id}" ${!ready||busy||selected!==next?'disabled':''}>${busy?'正在执行…':completed.includes(stage.id)?'本步已完成':'执行这一步'}</button>${selected<5?`<button class="btn ghost" data-lake-step="${selected+1}">阅读下一步 →</button>`:''}<span>${!ready?'先启动 MatrixOne。':selected>next&&next>=0?`先执行第 ${next+1} 步。`:record?h(record.result):'等待执行，结果区只显示本机返回。'}</span></div></div></div>
  <div class="lake-status" aria-live="polite"></div>${data?.empty_read_error&&selected===2?`<details><summary>本机空表首次读取的实际错误</summary><pre class="pitr-error">${h(data.empty_read_error)}</pre></details>`:''}
  ${selected===2&&data?.mapping_ddl?`<details class="lake-files"><summary>查看 SHOW CREATE TABLE 返回的映射定义</summary>${sqlBlock(data.mapping_ddl,'数据库实际 DDL')}</details>`:''}<p class="docs-hint">步骤卡保存各步执行时的记录；下方显示最近读取的本机状态。回看某一步不会回滚湖表。</p><div class="lake-facts"><div><small>湖上 namespace / table</small><strong>${h(data?.namespace||'尚未创建')} / append_orders</strong></div><div><small>四行时的表快照 ID</small><strong>${h(data?.old_snapshot||'写入后生成')}</strong></div><div><small>历史 Catalog 分支</small><strong>${h(data?.history_ref||'第 5 步创建')}</strong></div><div><small>main 当前表快照 ID</small><strong>${h(meta?.snapshot_id||'尚未提交数据')}</strong></div></div>
  <div class="lake-results"><div><span class="guide-mini-label">main / 本次读取 ${completed.includes('write')?data.current.length:'—'} 行</span>${completed.includes('write')?resultTable(['订单','bucket','金额','地区'],data.current):'<p>尚未写入数据快照；先完成第 4 步，再查询订单。</p>'}</div><div><span class="guide-mini-label">历史分支 / 本次读取 ${data?.historic?.length??'—'} 行</span>${completed.includes('history')?resultTable(['订单','bucket','金额','地区'],data.historic):'<p>第 5 步才创建历史映射。</p>'}</div></div>
  <details class="lake-files"><summary>看数据落在哪里：实际对象文件与元数据 <span>${files.length} 个对象</span></summary><p>以下来自 MinIO 对该表目录的真实列举。目录可能同时保留旧元数据或未被当前快照引用的文件，不能把目录文件数当作本次查询扫描文件数。标记“追加后新增”的文件是与四行时的目录对比所得。</p>${meta?`<dl><dt>metadata JSON</dt><dd>${h(meta.metadata_location)}</dd><dt>当前快照的 manifest list</dt><dd>${h(meta.snapshots.find(s=>s.id===meta.snapshot_id)?.manifest_list||'尚未写入')}</dd></dl>`:''}${files.length?resultTable(['对象文件','字节','与四行时对比'],files.map(([path,size])=>[path,size,completed.includes('append')&&!first.has(path)?'追加后新增':'已存在'])):'<p>创建湖表后显示实际文件。</p>'}</details>
  <div class="lake-actions"><button class="btn ghost" data-lake-action="inspect" ${!data||busy?'disabled':''}>重新读取 SQL 与元数据</button><button class="btn ghost" data-lake-action="restart" ${!ready||busy?'disabled':''}>从空湖表重新演示</button></div><p class="docs-hint">重新演示会生成新 namespace，后续映射步骤重建 demo_story_lake；已写入对象存储的旧演示文件会保留。本例是小型未分区表与 append_only 写入，未测试跨引擎并发或性能。</p>`;
}
export function renderIcebergLesson(state){const d=state.iceberg_tutorial;const n=ICEBERG_STAGES.findIndex(s=>!d?.completed.includes(s.id));return `<section class="lake-lesson" id="iceberg-lab" data-lake-lab>${caseSQL(view(d,done(state,'start'),n<0?0:n,0,false))}</section>`;}
export function wireIcebergLesson(root,state){const host=root.querySelector('[data-lake-lab]');if(!host)return;let data=state.iceberg_tutorial,selected=Math.max(0,ICEBERG_STAGES.findIndex(s=>!data?.completed.includes(s.id))),role=0,busy=false;const ready=done(state,'start');const render=()=>{host.innerHTML=caseSQL(view(data,ready,selected,role,busy));wireCopy(host);};host.addEventListener('click',async e=>{if(busy)return;const r=e.target.closest('[data-lake-role]'),s=e.target.closest('[data-lake-step]'),b=e.target.closest('[data-lake-action]');if(r){role=Number(r.dataset.lakeRole);render();return;}if(s){selected=Number(s.dataset.lakeStep);render();return;}if(!b)return;const action=b.dataset.lakeAction;if(caseId&&action!=='inspect'){document.getElementById('case-workbench')?.scrollIntoView();return;}busy=true;render();host.querySelector('.lake-status').textContent=action==='services'||action==='restart'?'正在检查 MinIO / Nessie，首次可能需要拉取镜像…':'正在执行本步，等待服务与数据库返回…';try{data=await api('iceberg',{action});if(action==='restart')selected=0;busy=false;render();host.querySelector('.lake-status').textContent='本机操作完成。先看本步结果，再阅读下一步。';}catch(error){busy=false;render();host.querySelector('.lake-status').textContent=error.message;}});}
